theme = "base16_default"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.'space'.'u']
'f' = ':format' # Format file using LSP formatter
'a' = '%|alejandra' # Format Nix using Alejandra
