name: CI

on: [push, workflow_dispatch]

jobs:
  cachix:
    name: Build Configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - homesv
        - io
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: fufexan
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel
